name: Node CI

on:
  schedule:
  - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: yarn install, upgrade, build, and test
      run: |
        yarn
        yarn upgrade --latest
        yarn build --if-present
        yarn test
